RETRIES: 6
CHECKPOINT_FREQUENCY: 10

OUTPUT_DIR: "data"
SCHOOL: "brown"
SUBJECT: "opinions"

BASE_URL: "https://www.browndailyherald.com"
LISTING_BASE_URL: "https://www.browndailyherald.com/section/opinions?per_page=20&page="
ARTICLE_SELECTOR: "div > h2.headline > a[href^='https://www.browndailyherald.com/article']"

TITLE_SELECTOR: "article.full-article > h1"
CONTENT_SELECTOR: "article.full-article > div.article-content"
DATE_SELECTOR: "aside > div > span.can-localize"

URL_DATE_PATTERN: "https://www.browndailyherald.com/article/(\\d+)/(\\d+)"
DATE_FORMAT: "%B %d, %Y"
