RETRIES: 6
CHECKPOINT_FREQUENCY: 10

OUTPUT_DIR: "data"
SCHOOL: "princeton"
SUBJECT: "opinion"

BASE_URL: "https://www.dailyprincetonian.com/section/opinion"
LISTING_BASE_URL: "https://www.dailyprincetonian.com/section/opinion?per_page=20&page="
ARTICLE_SELECTORS:
  ["article div a[href^='https://www.dailyprincetonian.com/article/']"]

TITLE_SELECTORS: ["div article.full-article > h1"]
CONTENT_SELECTORS: ["div article.full-article"]

DATE_SELECTOR: ""
DATE_FORMATS: ["%b %d, %Y", "%B %d, %Y", "%b. %d, %Y"]

URL_DATE_PATTERN: "https://www.dailyprincetonian.com/article/(\\d+)/(\\d+)"
