RETRIES: 6
CHECKPOINT_FREQUENCY: 10

OUTPUT_DIR: "data"
SCHOOL: "stanford"
SUBJECT: "opinions"

BASE_URL: "https://stanforddaily.com"
LISTING_BASE_URL: "https://stanforddaily.com/category/opinions/page/"
ARTICLE_SELECTORS:
  [
    "div > h3 > a[href^='https://stanforddaily.com/']",
    "div > h3 > a[href^='https://stanforddaily.com/']",
  ]

TITLE_SELECTORS: ["article div > h1.elementor-heading-title"]
CONTENT_SELECTORS: ["article div > div.e-con-inner"]
DATE_SELECTOR: "#date > div > span"
DATE_FORMATS: ["%b. %d, %Y", "%b %d, %Y", "%B %d, %Y"]

URL_DATE_PATTERN: "https://stanforddaily.com/(\\d+)/(\\d+)"
