RETRIES: 6
CHECKPOINT_FREQUENCY: 10

OUTPUT_DIR: "data"
SCHOOL: "uoregon"
SUBJECT: "opinion"

BASE_URL: "https://dailyemerald.com"
LISTING_BASE_URL: "https://dailyemerald.com/category/columns/page/"
ARTICLE_SELECTOR: "#content div > div > h2> a[href^='https://dailyemerald.com/']"

TITLE_SELECTOR: "div > div > h1.sno-story-headline"
CONTENT_SELECTOR: "#sno-story-body-content"
DATE_SELECTOR: "div.sno-story-date > span"

URL_DATE_PATTERN: "https://dailyemerald.com/"
DATE_FORMAT: "%B %d, %Y"
