RETRIES: 6
CHECKPOINT_FREQUENCY: 10

OUTPUT_DIR: "data"
SCHOOL: "uoregon"
SUBJECT: "opinion"

BASE_URL: "https://dailyemerald.com"
LISTING_BASE_URL: "https://dailyemerald.com/category/columns/page/"
ARTICLE_SELECTORS:
  [
    "#content div > div > h2> a[href^='https://dailyemerald.com/']",
    "#content div > div > h2> a[href^='https://dailyemerald.com/']",
  ]

TITLE_SELECTORS: ["div > div > h1.sno-story-headline"]
CONTENT_SELECTORS: ["#sno-story-body-content"]
DATE_SELECTOR: "div.sno-story-date > span"
DATE_FORMATS: ["%B %d, %Y", "%b. %d, %Y", "%b %d, %Y"]

URL_DATE_PATTERN: "https://dailyemerald.com/"
