RETRIES: 6
CHECKPOINT_FREQUENCY: 10

OUTPUT_DIR: "data"
SCHOOL: "utaustin"
SUBJECT: "opinions"

BASE_URL: "https://thedailytexan.com"
LISTING_BASE_URL: "https://thedailytexan.com/category/opinion/columns/page/"
ARTICLE_SELECTORS:
  [
    "div > h2 > a[href^='https://thedailytexan.com']",
    "div > h2 > a[href^='https://thedailytexan.com']",
  ]

TITLE_SELECTORS:
  ["#sno-main-content > div > div > h1[class^='sno-story-headline']"]
CONTENT_SELECTORS: ["#sno-story-body-content"]
DATE_SELECTOR: "#sno-main-content > div > div > div.sno-story-date > span"
DATE_FORMATS: ["%B %d, %Y", "%b. %d, %Y", "%b %d, %Y"]

URL_DATE_PATTERN: "https://thedailytexan.com/(\\d+)/(\\d+)"
