RETRIES: 6
CHECKPOINT_FREQUENCY: 1

OUTPUT_DIR: "data"
SCHOOL: "yale"
SUBJECT: "opinion"

BASE_URL: "https://yaledailynews.com/"
LISTING_BASE_URL: "https://yaledailynews.com/blog/category/opinion/page/"
ARTICLE_SELECTORS:
  ["div.category-article-list div a[href^='https://yaledailynews.com/']"]

TITLE_SELECTORS: ["#article-content article div.article-header h1"]
CONTENT_SELECTORS: ["#article-content article"]

DATE_SELECTOR: ""
DATE_FORMATS: ["%b %d, %Y", "%B %d, %Y", "%b. %d, %Y"]

URL_DATE_PATTERN: "https://yaledailynews.com/blog/(\\d+)/(\\d+)"
